### ISSUE TITLE
Getting Invalid Syntax

### ISSUE THREAD

**Issue by mobbyg** [opicron/utf2ascii#1]
So I am trying to use this neat tool to clean up a file and remove UTF for my BBS. But I am getting a syntax error and I maybe I am missing something on usage. 

pi@raspberrypi:~/Documents/fr_test $ python3 utf2ascii.py
  File "utf2ascii.py", line 155
    p1 = re.compile(ur'\xe2[\x00-\xFF][\x00-\xFF]' , re.UNICODE) #"/[\x{2600}-\x{267F}]/u"  #in the range [\x{2600}-\x{267F}] (i.e. U+2600 to U+267F) # for future use
                                                 ^
SyntaxError: invalid syntax

It seems to be indicating the comma after the second RegEx group is not supposed to be there. 
But I can say I am not exactly the best for Python myself. I added some code to load a text file, run it through the def utf2ascii() and then take the "santized" text and write it back to a new file.

**Comment by opicron** [comment]
Sorry for slow delay, you need to tell Python to parse the scripts as Unicode.

**Comment by opicron** [comment]
I updated the code.
